// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/geomoz-dark/DarkGIS.tsx": () => import("../components/mockups/geomoz-dark/DarkGIS.tsx"),
  "./components/mockups/geomoz-light/LightDashboard.tsx": () => import("../components/mockups/geomoz-light/LightDashboard.tsx")
};
